name 'delivery-github-demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures delivery-github-demo'
long_description 'Installs/Configures delivery-github-demo'
version '0.1.1'
